Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "DontVTSwitch" "true"
    Option "AllowMouseOpenFail" "true"
EndSection
Section "Device"
    Identifier "LocalDummy"
    Driver "dummy"
    VideoRam 256000
EndSection
Section "Monitor"
    Identifier "LocalMonitor"
    HorizSync 30-90
    VertRefresh 50-75
    Modeline "1600x900" 118.25 1600 1696 1856 2112 900 903 908 934 -HSync +VSync
EndSection
Section "Screen"
    Identifier "LocalScreen"
    Device "LocalDummy"
    Monitor "LocalMonitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1600x900"
        Virtual 1600 900
    EndSubSection
EndSection
